name: 'run commands on aws using github-action-role'

on:
    push:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::607089492772:role/github-action-role
        aws-region: us-east-2

    - name: run command
      run: |
        aws sts get-caller-identity
